# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - gwo-viewer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_341df3e7a4a945b2a397549868f232fa }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d3232dba19b74f93b4d58e9bd751845b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_341df3e7a4a945b2a397549868f232fa }}/gwo:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gwo-viewer'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c2f0bf91ee7d4f58bfca8354a56f45fd }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_341df3e7a4a945b2a397549868f232fa }}/gwo:${{ github.sha }}'